version: '3'

services:
  db:
    image: mysql:5.7
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  app:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    tty: true
    environment:
      FLASK_ENV: development
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
      MYSQL_NAME: flask-api-example_development
